CREATE DATABASE IF NOT EXISTS fanak;
CREATE DATABASE IF NOT EXISTS keycloak;

CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON fanak.* TO 'admin'@'%';
GRANT ALL PRIVILEGES ON keycloak.* TO 'admin'@'%';
FLUSH PRIVILEGES;